### ISSUE TITLE
Spotify output disapear after the count 

### ISSUE THREAD

**Issue by jonathashenriques** [jaagr/lemonbuddy#105]
After install the last version of lemonbuddy my spotify script does not work anymore. The output disappear after the count (in this case set to 100). Script link: http://pastebin.com/CPCRj4tk

**Comment by jonathashenriques** [comment]
Note: If i try without scroller it works flawless.

**Comment by jonathashenriques** [comment]
Note: after the update, the script stoped working at all. Even calling it from the terminal the crash  happens after the count.

**Comment by jaagr** [comment]
Hi, could you show me the module configuration that uses the script

**Comment by jaagr** [comment]
The script works fine (i removed scroller since I don't have it installed) and the sleep calls since it can be specified in the configuration instead.

~~~ini
[module/spotify]
type = custom/script
exec = ~/sandbox/spotify-test
interval = 10
~~~

**Comment by jonathashenriques** [comment]
Hi, without "tail", the module just dont appear .The module is:

[module/Spotify]
type = custom/script
exec = ~/.config/lemonbuddy/Scripts/Spotify/Spotify.sh
tail = true
format-padding = 2
format-foreground = ${bar/Bar.foreground}
format-foreground = ${bar/Bar.background}
format-background = #0d000000
format-overline = ${bar/Bar.background}
format-underline = ${bar/Bar.background}

**Comment by jonathashenriques** [comment]
Can you please add a truncate/ellipsis text function to custom modules ? I only use scroller for this.

**Comment by jaagr** [comment]
Could you try the script without both scroller and the sleep's and `tail = false`

~~~sh
#!/bin/bash
#
# Show Spotify current song

spotifyon=$(ps -e |grep spotify)
if [ -z "$spotifyon" ]; then
	echo ""
else
artist=`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'|egrep -A 2 "artist"|egrep -v "artist"|egrep -v "array"|cut -b 27-|cut -d '"' -f 1|egrep -v ^$`
title=`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'|egrep -A 1 "title"|egrep -v "title"|cut -b 44-|cut -d '"' -f 1|egrep -v ^$`
	echo "|" $artist "-" $title
fi
~~~
~~~

**Comment by jaagr** [comment]
The script module already have maxlen and ellipsis options. See the wiki

**Comment by jonathashenriques** [comment]
I removed scroller and sleep but, with tail = false the bar does not appear.

**Comment by jonathashenriques** [comment]
And sadly the ellipsis is not working.

**Comment by jaagr** [comment]
Are you using the latest version?

**Comment by jonathashenriques** [comment]
Yeah, the test module just works fine.

**Comment by jonathashenriques** [comment]
Just in case you dont understand my bad english: https://github.com/kbrgl/scroller

**Comment by jaagr** [comment]
It should be fixed now... Please verify..
Notes: 
- Use `tail = true` to tail the scroller output
- Remove `sleeps`
- Set `interval = N` in the module config instead

**Comment by jonathashenriques** [comment]
Thanks for the support, it was awesome. Now i have the module showing, even if its turn on and off all the time (i can live with that) but, the cpu usage increased a lot. Anyway, again thanks, i really appreciate your job.

**Comment by jaagr** [comment]
yes I just noticed the cpu usage... looks like a spin lock that's not, i will patch it

**Comment by jonathashenriques** [comment]
If i set scroller count to 10, for example, cpu usage increase to 20%/30%. This is okay, but the module looks like the christimas lights.

**Comment by jaagr** [comment]
Not really sure how you want it to be displayed.. but this works fine for me.. no noticable cpu usage

~~~ini
[module/spotify]
type = custom/script
; all of this could of course be put in a single script... or just move the piping to the spotify script
exec =  ~/bin/spotify_status.sh %artist% - %title% | while read -r status; do echo $status | scroller -c $((${#status}*2)) -i 0.2 -s "   --   "; do
; tail since scroller will output continuously
tail = true
; when the script has ended, wait this time and then launch it again
interval = 2
~~~

~~~sh
#!/bin/sh
main() {
  if ! pgrep -x spotify >/dev/null; then
    echo "spotify is off"; exit
  fi

  cmd="org.freedesktop.DBus.Properties.Get"
  domain="org.mpris.MediaPlayer2"
  path="/org/mpris/MediaPlayer2"

  meta=$(dbus-send --print-reply --dest=${domain}.spotify \
    /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:${domain}.Player string:Metadata)

  artist=$(echo "$meta" | sed -nr '/xesam:artist"/,+2s/^ +string "(.*)"$/\1/p' | tail -1)
  album=$(echo "$meta" | sed -nr '/xesam:album"/,+2s/^ +variant +string "(.*)"$/\1/p' | tail -1)
  title=$(echo "$meta" | sed -nr '/xesam:title"/,+2s/^ +variant +string "(.*)"$/\1/p' | tail -1)

  echo "${*:-%artist% - %title%}" | sed "s/%artist%/$artist/g;s/%title%/$title/g;s/%album%/$album/g"
}

main "$@"
~~~

**Comment by jonathashenriques** [comment]
Everything is working fine now, thank you so much. Keep the awesome work.

**Comment by Subzidion** [comment]
This breaks if the artist or title has an & in it. For example, The Civil Wars - Poison & Wine would show as "The Civil Wars - Poison %title% Wine" instead. I just changed it to `echo $artist - $title` and it seems to work, but I get a feeling you used sed for a reason. If there's a reason to use sed or a better way to do it, I'd appreciate an update. Thanks for all the work you've put into this!

**Comment by jaagr** [comment]
That syntax was used to be able to pass the format to the script `./script %title% %artist% %album%`

You probably have to escape the ampersand. Try:

~~~sh
... | sed 's/&/\\&/g'
