### ISSUE TITLE
Issues with offset and width

### ISSUE THREAD

**Issue by z1lt0id** [jaagr/lemonbuddy#39]
I've been getting *invalid geometry specified* when running lemonbuddy_wrapper.  What I really want to do is have the bar centre top with a 25 pixel y offset.  But I'm not sure what I've done wrong.  Below is a link to the config file.

https://bin.fsociety.info/imivawudoz

**Comment by patrick96** [comment]
With the config you provide, I do not get the error.
However, if I uncomment the `offset_x` setting, the error appears too, this is because the bar would be outside of the screen.
You are using a very high `offset_x` value, so I assume you do it to make it appear on another screen. You should use the `monitor` property in the bar section to do that. To get the monitor names, run `xrandr -q | grep " connected" | cut -d ' ' -f1`.

**Comment by z1lt0id** [comment]
I should mention I have a monitor resolution of 3440x1440.  It is in a ultra wide 21:9 monitor. So having it around the 1100 would actually make it centered on my monitor.

**Comment by patrick96** [comment]
Do you get the error with the exact config you provided, so without the `offset_x`?
By only using center modules, the bar should already be perfectly centered, shouldn't it, or did I understand something wrong?

**Comment by z1lt0id** [comment]
I actually found out what the problem was, it was because i wasn't using lemonbar-sm-xft fork. I'll close the issue.  It works fine now.

**Comment by patrick96** [comment]
Ah yes, I've been meaning to ask about that
