### ISSUE TITLE
Icon not aligned

### ISSUE THREAD

**Issue by Bl4ckb0ne** [jaagr/lemonbuddy#47]
![lemonbuddy icon](http://imgur.com/Ddgrbws.png)

Here are my fonts
``` sh
font-0 = NotoSans-Regular:size=16;0 
font-1 = MaterialIcons:size=16;0 
font-2 = Termsynu:size=16;0 
font-3 = FontAwesome:size=16;0 
```
Is it a known problem, or just my icon font?

**Comment by patrick96** [comment]
You can actually define an offset per font so that all of the text from that font is moved up/down by that many pixels. The offset is the number after the semicolon when defining the font (positive means down and negative means up).
The icon looks like its from FontAwesome so you could do something like this and then just tweak the offset until it is right for you.
`font-3 = FontAwesome:size=16;-1`

**Comment by Bl4ckb0ne** [comment]
I finally got the icons centered, thanks for the tips.

You should add more about the fonts in the readme, the section is a _TODO_.

**Comment by patrick96** [comment]
The [Bar Settings](https://github.com/jaagr/lemonbuddy#bar-settings) section actually mentions that the number after the semicolon is the offset. But you're right the README has a few TODO sections, but I'm leaving that up to jaagr since he has a much better grasp at how things should work

**Comment by Bl4ckb0ne** [comment]
Oops, I think I missed it.

Anyway, thanks for your help
