### ISSUE TITLE
Possible to set max lenght for song label?

### ISSUE THREAD

**Issue by Traverse** [jaagr/lemonbuddy#49]
Hi I was wondering if it's possible to set a max length for the song label? I haven't found the option anywhere and in my opinion it would be nice to have. So might be a possible enhancement or just me being blind. :smile:

**Comment by patrick96** [comment]
This is currently not possible. Do you have problems where the mpd module grows too big and covers other modules?
If so, you can place the module on the left or the center, because lemonbar will favor the parts on the right if there is overlap. If you put it in the center, it should be the only module there, and on the left it should be the last module listed
This would indeed be nice to have, I'll keep it in mind, can't make any promises as to when or if though.

**Comment by Traverse** [comment]
It's not really a problem with it overlapping other things it's more about the aesthetics of it. I really dislike when the modules move all over.

**Comment by patrick96** [comment]
Alright, what you can do is create a text module with only whitespace and place it in the module list that is on the right of the mpd module (if the mpd module is on the left put the whitespace module in the center and if it is in the center put the whitespace module on the right side) and make sure the whitespace module is the first in the list. This will make the whitespace module take precendent if it overlaps with the mpd module.
It is a dirty hack, I know ^^

**Comment by Traverse** [comment]
I guess it's a solution for now albeit hacky. :wink:

**Comment by patrick96** [comment]
Yes really hacky, and you will need to tweak it if you ever change fonts, font size, monitor resolution or bar size
But whitespace modules can be really useful, I use on to make space for a system tray ;)
