### ISSUE TITLE
[Question] How to configure the bar to use separators like powerline does?

### ISSUE THREAD

**Issue by shackra** [jaagr/lemonbuddy#52]

**Comment by patrick96** [comment]
It is not going to be easy. There is no built in setting for that and since lemonbuddy does not support different separators for the left, right and center modules, you will have to set the separator to an empty string and add the powerline separators at the end (or the start) of each module by yourself, you will also need to set the colors yourself.

**Comment by shackra** [comment]
I see, thanks!

El lunes 29 de agosto del 2016 a las 0250 horas, Patrick Ziegler escribió:

> It is not going to be easy. There is no built in setting for that and since lemonbuddy does not support different separators for the left, right and center modules, you will have to set the separator to an empty string and add the powerline separators at the end (or the start) of each module by yourself, you will also need to set the colors yourself.


--
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by patrick96** [comment]
When you get a decent version, I (and probably others too) would be interested to see it. Just post it here, but for now, I think you can close this.

**Comment by binaryplease** [comment]
A bit late to the party, but I'm trying to figure out how to do this. I've got the nerd patched fonts installed and the separators seem to work correctly. My only issue is that the separators are now it's own block. While this works fine when the modules around it are shown, you get redundant separators if not. I use my polybar configuration on both a tower pc and a laptop. The brightness module e.g. only works on the laptop obviously. This never was a problem, since it's just disabled silently on the tower. With extra separator blocks you get this when it's empty:


![image](https://user-images.githubusercontent.com/1719781/59484984-4f579080-8e74-11e9-9c69-ade571a4a3db.png)
Is there a better way to do this separators?

**Comment by patrick96** [comment]
You'll have to prefix and suffix every module individually.

**Comment by binaryplease** [comment]
@patrick96 I see. Is it possible to combine environment variables with strings in the format or prefix of a module?
I defined a environment variable as shown in the docs in my polybar lauch script like this:
``` bash

#!/bin/bash

killall polybar
while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done

export BAR_LABEL_SEPARATOR="%{T5}%{F$(xrdb -query | grep "*.color14" | cut -f 2)}%{F-}%{T-}"

for i in $(polybar -m | awk -F: '{print $1}'); do MONITOR=$i polybar primary -c ~/.config/polybar/config & done
```
I then use it in a module like this:
```
[module/memory]
type = internal/memory
interval = 2
format-prefix = ${env:BAR_LABEL_SEPARATOR}

format-underline = ${colors.color-line-5}
label = %percentage_used%%

format-background = ${colors.color8}
foreground = ${colors.foreground}
```

This works fine without any aditional text in the `format-prefix = ` varaible, it looks like this:
![image](https://user-images.githubusercontent.com/1719781/59487117-fd1a6d80-8e7b-11e9-97bb-4ebb833eb177.png)

What I really want though, is to have (additionally to the separator) a prefix character, like I was using before. If I change the module's configuration to this:
```
[module/memory]
type = internal/memory
interval = 2
format-prefix = "${env:BAR_LABEL_SEPARATOR} "
format-underline = ${colors.color-line-5}
label = %percentage_used%%

format-background = ${colors.color8}
foreground = ${colors.foreground}
```
(notice the added icon) the environment variable is no longer interpreted correctly resulting in this output:

![image](https://user-images.githubusercontent.com/1719781/59487222-410d7280-8e7c-11e9-8d3c-9cb10a0746e0.png)

Is it possible to use a separator **and* a icon? if so, how?
I don't want to put the actual hex color in the config itself, since the way it's set up now allows me to switch colorthemes easily changing only the xresources file.

**Comment by patrick96** [comment]
>Is it possible to combine environment variables with strings in the format

No, that's the same limitation as using variables inside formatting tags. You will have to define an env variable that contains the entire prefix and reference that.

**Comment by binaryplease** [comment]
I found a (a bit messy) solution:
```
[module/memory]
type = internal/memory
interval = 2
format-prefix = ${env:BAR_LABEL_SEPARATOR}
format =  <label>


format-underline = ${colors.color-line-5}
label = %percentage_used%%

format-background = ${colors.color8}
foreground = ${colors.foreground}
```
Would it be possible to add functionality for better separators? While the above works, it seems like misusing the prefix field for a separator is not very elegant. It would be nice to be able to define left and right separators on per-module basis.
Result with the above:
![image](https://user-images.githubusercontent.com/1719781/59487858-2fc56580-8e7e-11e9-9f62-b49e0ec8bedf.png)

**Comment by patrick96** [comment]
You can set `separator` in the [bar section](https://github.com/polybar/polybar/wiki/Configuration#bar-settings) to define the separator between any two modules.
