### ISSUE TITLE
Two Issues: Multi-Monitor & custom/script

### ISSUE THREAD

**Issue by WhatsCS** [jaagr/lemonbuddy#77]
Using the new config under 2.0 for bspwm. I have the following:
```
[module/bspwm]
type = internal/bspwm
ws-icon-default = 

label-active =  
label-active-padding = 2

label-occupied = 
label-occupied-padding = 2

label-urgent = 
label-urgent-background = #bd2c40
label-urgent-padding = 2

label-empty = 
label-empty-foreground = #444
label-empty-padding = 2


[module/xtitle]
type = custom/script
exec = xtitle -s
tail = true
maxlen = 25
```
bspwmrc:
```
bspc monitor VGA-1 -n 0 -d I II III IV V
bspc monitor VGA-2 -n 1 -d VI VII VIII IX X
```

Issue: I am only getting workstations I-V showing up. bspwm's example panel config has settings that show the monitor number then I-V monitor number VI-X. Example:
![desktop bar](https://catgirl.pics/i/teZhq6.png)

The second issue I'm having is that `[module/xtitle]` isn't displaying. I'll link a pastebin of `lemonbuddy test -l info -s`
[output.log](http://hastebin.com/giquyahicu)

**Comment by Vintodrimmer** [comment]
Same here with xtitle

**Comment by jaagr** [comment]
Hi and thanks for reporting.

Regarding bspwm:

This is the way I built the bspwm module. I also have a multi-monitor setup but I have a separate bar on each monitor so I only wanted to show the workspaces for the current monitor on the bar.

I could of course implement a config option to change this behaviour if there's need for it, but at the moment I will focus on fixing bugs so that we can release a stable 2.0 version.

Regarding the script module I will need to test this, so I will come back to it.

**Comment by jaagr** [comment]
The issue with xtitle should now be fixed. Please re-open otherwise.
